[ai]
include_convention = true
include_file_tree = true
include_git_status = true
include_untracked = true
files_to_truncate = []

[ai.providers.Claude]
enable = false
model = "claude-3-5-haiku"
max_tokens = 5000

[ai.providers.OpenAI]
enable = false
model = "gpt-5-nano"
max_tokens = 5000

[ai.providers.Gemini]
enable = false
model = "gemini-2.5-flash-lite"
max_tokens = 5000

[ai.rules]
group_related_files = true
no_file_splitting = true
separate_by_purpose = true
verbose_descriptions = true
exclude_extension_in_scope = true
allow_empty_scope = true
max_header_length = 52
max_body_length = 72

[gai]
stage_hunks = false

[gai.commit_config]
capitalize_prefix = true
include_scope = true
include_breaking = true

[tui]
auto_request = false
skip_splash = false
