auto_request = false
skip_splash = true
include_untracked = true
stage_hunks = false
api_key_file = ""
files_to_truncate = [
    "Cargo.lock",
    "package-lock.json",
]

[ai]
capitalize_prefix = false
include_scope = true
system_prompt = "You are an expert at git operations.Create git a logical list of git commits based on diffs and structure."
include_convention = true

[ai.rules]
group_related_files = true
no_file_splitting = true
separate_by_purpose = true
verbose_descriptions = true
exclude_extension_in_scope = true
allow_empty_scope = true

[ai.openai]
enable = true
model_name = "gpt-5-mini-2025-08-07"
max_tokens = 5000

[ai.gemini]
enable = true
model_name = "gemini-2.5-flash"
max_tokens = 5000

[ai.claude]
enable = false
model_name = "claude-3-5-haiku-latest"
max_tokens = 5000
